# Generated by Django 5.2.5 on 2025-10-11 07:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calls', '0002_room_remove_call_room_no_call_room'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hospital',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='room',
            name='floor_no',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='call',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='calls.room'),
        ),
        migrations.AlterField(
            model_name='room',
            name='room_no',
            field=models.CharField(max_length=10),
        ),
        migrations.AddField(
            model_name='room',
            name='hospital',
            field=models.ForeignKey(default='Fortis', on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='calls.hospital'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='room',
            unique_together={('hospital', 'room_no')},
        ),
    ]
